<?php
if ( ! defined( 'ABSPATH' ) ) exit;

/**
 * Register Gutenberg blocks
 */
function proevent_register_blocks() {

    // Safely include asset file (generated by wp-scripts build)
    $asset_path = get_template_directory() . '/dist/event-grid.asset.php';
    if ( ! file_exists( $asset_path ) ) {
        return;
    }
    $asset_file = include $asset_path;

    // Register block script
    wp_register_script(
        'proevent-event-grid',
        get_template_directory_uri() . '/dist/event-grid.js',
        $asset_file['dependencies'],
        $asset_file['version'],
        true
    );

    // Register block editor styles (for Gutenberg)
    $editor_style_path = get_template_directory() . '/dist/event-grid-editor.css';
    if ( file_exists( $editor_style_path ) ) {
        wp_register_style(
            'proevent-event-grid-editor',
            get_template_directory_uri() . '/dist/event-grid-editor.css',
            [],
            filemtime( $editor_style_path )
        );
    }

    // Register block type
    register_block_type( 'proevent/event-grid', [
        'editor_script'   => 'proevent-event-grid',
        'editor_style'    => 'proevent-event-grid-editor',
        'render_callback' => 'proevent_render_event_grid',
        'attributes'      => [
            'limit' => [
                'type'    => 'number',
                'default' => 6,
            ],
            'category' => [
                'type'    => 'string',
                'default' => '',
            ],
            'order' => [
                'type'    => 'string',
                'default' => 'ASC',
            ],
        ],
    ] );
}
add_action( 'init', 'proevent_register_blocks' );

/**
 * Render callback for Event Grid block
 */
function proevent_render_event_grid( $attributes ) {

    $args = [
        'post_type'      => 'event', // CPT: event
        'posts_per_page' => intval( $attributes['limit'] ),
        'orderby'        => 'meta_value',
        'meta_key'       => 'event_date',
        'order'          => $attributes['order'],
        'meta_query'     => [
            [
                'key'     => 'event_date',
                'value'   => date( 'Ymd' ),
                'compare' => '>=',
                'type'    => 'NUMERIC',
            ],
        ],
    ];

    // If category filter is set
    if ( ! empty( $attributes['category'] ) ) {
        $args['tax_query'] = [
            [
                'taxonomy' => 'event-category',
                'field'    => 'slug',
                'terms'    => sanitize_text_field( $attributes['category'] ),
            ],
        ];
    }

    $query = new WP_Query( $args );

    if ( ! $query->have_posts() ) {
        return '<p>' . esc_html__( 'No events found.', 'proevent' ) . '</p>';
    }

    ob_start();

    echo '<div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">';
    while ( $query->have_posts() ) {
        $query->the_post();
        // Gumamit ng template part para modular
        get_template_part( 'parts/event-card' );
    }
    echo '</div>';

    wp_reset_postdata();

    return ob_get_clean();
}

/**
 * Enqueue Tailwind CSS for frontend
 */
function proevent_enqueue_tailwind() {
    $style_path = get_template_directory() . '/dist/style.css';
    if ( file_exists( $style_path ) ) {
        wp_enqueue_style(
            'proevent-tailwind',
            get_template_directory_uri() . '/dist/style.css',
            [],
            filemtime( $style_path )
        );
    }
}
add_action( 'wp_enqueue_scripts', 'proevent_enqueue_tailwind' );

/**
 * Enqueue Tailwind CSS for block editor
 */
function proevent_enqueue_editor_tailwind() {
    $style_path = get_template_directory() . '/dist/style.css';
    if ( file_exists( $style_path ) ) {
        wp_enqueue_style(
            'proevent-tailwind-editor',
            get_template_directory_uri() . '/dist/style.css',
            [],
            filemtime( $style_path )
        );
    }
}
add_action( 'enqueue_block_editor_assets', 'proevent_enqueue_editor_tailwind' );
